### ISSUE TITLE
run_test.py fail with all examples

### ISSUE THREAD

**Issue by ig-d** [yijiangh/InverseCSG#1]
Hi,

I am trying to use the code after doing the manual installation (in Debian) that was successful but running the examples fails with the following error:
```
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    sketch_pipeline.RunSketchPipeline()
  File "/home//remove/csg/InverseCSG-master/sketch_pipeline.py", line 717, in RunSketchPipeline
    point_cloud_seg.SegmentPointCloud(part_file, seg_num, \
  File "/home//remove/csg/InverseCSG-master/point_cloud_seg.py", line 25, in SegmentPointCloud
    cluster_result.fit(points)
  File "/home//.local/lib/python3.8/site-packages/sklearn/cluster/_agglomerative.py", line 834, in fit
    X = self._validate_data(X, ensure_min_samples=2, estimator=self)
  File "/home//.local/lib/python3.8/site-packages/sklearn/base.py", line 421, in _validate_data
    X = check_array(X, **check_params)
  File "/home//.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home//.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 669, in check_array
    raise ValueError("Found array with %d sample(s) (shape=%s) while a"
ValueError: Found array with 1 sample(s) (shape=(1, 3)) while a minimum of 2 is required by AgglomerativeClustering
```

Checking the code, it points to the call of 
```
cluster_result = cluster.AgglomerativeClustering(n_clusters = seg_num)
cluster_result.fit(points)
```
The problem is that `points` just contain a point and `AgglomerativeClustering` fails since it expects at least two.

Note this happens after
```
if not sketch_done or '[SKETCH] DONE' not in open(sketch_output_file).read():
      helper.PrintWithRedColor('Problem is too hard. Need segmentation.')
      return '', False
```
is called.

Note I have tried to run it with most the given examples but failed:
```
python3 run_tests.py <path> one_cube
python3 run_tests.py <path> ex_011
python3 run_tests.py <path> ex_067
```

Note I found the same issue https://github.com/antonymarion/inverseCSG/issues/4

How can we address this?

Thanks!

**Comment by ig-d** [comment]
To give more context:
- I have tried to use sketch from git-hub ```git clone https://github.com/asolarlez/sketch-frontend.git``` as well as the latest version from https://people.csail.mit.edu/asolar/
- When running it appears many times:
```
/home//InverseCSG-master/build/cpp/csg_cpp_command remove-prim -e 0.100000 -i /home/csg/one_cube/points/surface_primitives_1086_0.prim -o /home/csg/one_cube/points/surface_primitives_1086_0.prim -n /home/csg/one_cube/points/neg_1086_0.data -p /home/csg/one_cube/points/pos_1086_0.data -v
command::RemovePrimCommand: 4 primitives at the beginning.
command::RemovePrimCommand: collected 1 positive equivalence classes. Key size = 1 chars.
command::RemovePrimCommand: collected 8 negitive equivalence classes. Key size = 1 chars.
command::RemovePrimCommand: equivalence class 0 1 0 1 is both inside and outside the mesh. The problem is UNSAT.
```
I guess this makes to kick `Problem is too hard. Neeed segmentartion`, and it iterates until just one point is left and produces the aforementioned error.

**Comment by WaferLi** [comment]
I meet the same problem as you.
How did you address it? 
thx

**Comment by ig-d** [comment]
I did not manage to address it, it seemed to require a major refactoring.
Maybe the authors could weight in here on how to address it.

Thanks

**Comment by Maksimo007** [comment]
Unfortunately, I also have the same problem. Is there a solution in the meantime?

**Comment by keckj** [comment]
Same, no example is working for me.
